books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('author/add/', views.AuthorAddView.as_view(), name='author_add'),
    path('', views.BookView.as_view(), name='book'),
    path('add/', views.BookAddView.as_view(), name='book_add'),
    path('<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:id>/comment/', views.BookCommentView.as_view(), name='book_comment')
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('', views.index, name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import Register, Login, Loguot, Profile, ProfileEdit

app_name = 'users'

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Loguot.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-edit/', ProfileEdit.as_view(), name='profile-edit')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    profile_pic = models.ImageField(upload_to='profile_pics', default='default_profile_pic.jpeg')


    def check_hash_password(self):
        if not self.password.startswith('pbkdf2_sha256'):
            self.set_password(self.password)
        
    def save(self, *args, **kwargs):
        self.check_hash_password()
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from .models import User

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=155)
    password = forms.CharField(max_length=43)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_pic')

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreateForm, LoginForm,ProfileUpdateForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .models import User
from django.contrib.auth.mixins import LoginRequiredMixin

class Register(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {'form': create_form}
        return render(request, 'register.html', context=context)
    
    def post(self, request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect(reverse_lazy('users:login'))
        else:
            context = {
                'form': create_form
            }
            return render(request, 'login.html', context)

class Login(View):
    def get(self, request):
        login_form = LoginForm()
        context = {'form': login_form}
        return render(request, 'login.html', context=context)
    
    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            print(user)
            login(request, user)
            return redirect(reverse_lazy('home'))
        else:
            context = {'form': login_form}
        return render(request, 'login.html', context=context)
    
class Loguot(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('users:login')
    

class Profile(LoginRequiredMixin, View):
    def get(self, request):
        user = User.objects.get(id=request.user.id)
        print(user)
        context = {'user': user}
        return render(request, 'profile.html', context=context)
    

class ProfileEdit(LoginRequiredMixin, View):
    def get(self, request):
        user_update = ProfileUpdateForm(instance=request.user)
        return render(request, 'profile-edit.html', {'form': user_update})

    def post(self, request):
        user_update = ProfileUpdateForm(instance=request.user, data=request.POST, files=request.FILES)
        if user_update.is_valid():
            user_update.save()
            return redirect('users:profile')

        return render(request, 'profile.html', {"form": user_update})

users/templates/login.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
            {{form|crispy}}
        <button type="submit">Login</button>
    </form>
</body>
</html>

users/templates/profile-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}

<h1 class="middle">Profile Page Edit</h1>
<form class="middle" method="post" action="{% url 'users:profile-edit' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}

    <button class="btn1 btn-outline-primary">save changes</button>
</form>

{% endblock %}

users/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class="image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img src="{{ user.profile_pic.url }}" height="100" width="100" />
            </button>
            <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
            <span class="idd"></span>
            <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                <span class="idd1">{{ user.username }}</span>
                <span><i class="fa fa-copy"></i></span>
            </div>
            <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                <span class="number"><span class="follow"></span></span>
            </div>
            <div class="d-flex mt-2">
                <a style="text-align: center;" href="{% url 'users:profile-edit' %}" class="btn1 btn-dark">Edit Profile</a>

            </div>
            <div class="text mt-3">
                <span>Eleanor Pena is a creator of minimalistic x bold graphics and digital artwork.<br><br>
                Artist/ Creative Director by Day #NFT minting@ with FND night.</span>
            </div>
            <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center">
                <span><i class="fa fa-twitter"></i></span>
                <span><i class="fa fa-facebook-f"></i></span>
                <span><i class="fa fa-instagram"></i></span>
                <span><i class="fa fa-linkedin"></i></span>
            </div>
            <div class="px-2 rounded mt-4 date">
                <span class="join">{{ user.date_joined|date:"M d, Y" }}</span>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/register.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register</h1>
    <form class="middle" method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
            {{form|crispy}}
        <button type="submit">Send</button>
    </form>
</body>
</html>