books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('author/add/', views.AuthorAddView.as_view(), name='author_add'),
    path('', views.BookView.as_view(), name='book'),
    path('add/', views.BookAddView.as_view(), name='book_add'),
    path('<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:id>/comment/', views.BookCommentView.as_view(), name='book_comment')
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('', views.index, name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class Book(models.Model):
    author = models.ForeignKey('books.Author', on_delete=models.CASCADE, related_name='books')
    title = models.CharField(max_length=255)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_pic = models.ImageField(default='default_cover_pic.png', upload_to='books_images')

    def __str__(self) -> str:
        return f'{self.author.first_name} {self.title}'
    

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    bio = models.TextField()
    def __str__(self) -> str:
        return self.first_name
    

class BookComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    star_given = models.IntegerField(validators=[MaxValueValidator(1), MinValueValidator(5)])
    creted_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.comment

books/forms.py
from django import forms
from .models import Book, Author, BookComment


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'email', 'bio']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'description', 'isbn', 'cover_pic']
        

class BookCommentForm(forms.ModelForm):
    class Meta:
        model = BookComment
        fields = ['comment', 'star_given']

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AuthorForm, BookForm, BookCommentForm
from django.views import View
from .models import Author, Book, BookComment
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

class AuthorView(LoginRequiredMixin, View):
    def get(self, request):
        author = Author.objects.all()
        context = {'authors': author}
        return render(request, 'author.html', context=context)

class AuthorAddView(LoginRequiredMixin, View):
    def get(self, request):
        form = AuthorForm()
        return render(request, 'author_add.html', context={'form': form})

    def post(self, request):
        form = AuthorForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("books:author")
        else:
            return render(request, 'author_add.html', context={'form': form})

class BookView(LoginRequiredMixin, View):
    def get(self, request):
        book = Book.objects.all()
        context = {'books': book}
        return render(request, 'book.html', context=context)

class BookAddView(LoginRequiredMixin, View):
    def get(self, request):
        form = BookForm()
        return render(request, 'book_add.html', context={'form': form})

    def post(self, request):
        form = BookForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect("books:book")
        else:
            return render(request, 'book_add.html', context={'form': form})

class BookDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        form = BookCommentForm()
        context = {'book': book, 'form': form}
        return render(request, 'book_detail.html', context=context)
    

class BookCommentView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        form = BookCommentForm(data=request.POST, instance=book)
        if form.is_valid():
            BookComment.objects.create(
                user=request.user,
                book=book,
                comment=form.cleaned_data.get('comment'),
                star_given=form.cleaned_data['star_given']
            )
            return redirect(reverse('books:book_detail', kwargs={'id': book.id}))
        return render(request, 'book_detail.html', {'book': book, 'form': form})

books/templates/author.html
{% extends 'base.html' %}
{% block title %}Authors Page{% endblock title %}
{% block content %}
<div class="middle mt-5">
    <table class="table table-bordered border-primary">
        <thead>
          <tr>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Email</th>
            <th scope="col">Bio</th>
          </tr>
        </thead>
        <tbody>
            {% for author in authors %}
          <tr>
            <td>{{author.first_name}}</td>
            <td>{{author.last_name}}</td>
            <td>{{author.email}}</td>
            <td>{{author.bio | slice:"100"}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
</div>
{% endblock content %}

books/templates/author_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Author Add Page{% endblock title %}
{% block content %}
<h1 class="middle mt-3 mb-3">Author Add</h1>
<form class="middle-form" action="{% url 'books:author_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Send</button>
</form>
{% endblock content %}

books/templates/book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Books{% endblock title %}
{% block content %}
<h1 class="middle mt-3 mb-3">Books</h1>
<div class="container">
    <div class="row">
        {% for book in books %}
        <div class="col-md-3 mb-4">
            <div class="card h-100">
                <img src="{{ book.cover_pic.url }}" class="card-img-top" alt="{{ book.title }} cover">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'books:book_detail' id=book.id %}">{{ book.title }}</a></h5>
                    <p class="card-text">{{ book.description | slice:100 }}</p>
                </div>
            </div> 
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

books/templates/book_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Book Add Page{% endblock title %}
{% block content %}
<h1 class="middle mt-3 mb-3">Book Add</h1>
<form class="middle-form" action="{% url 'books:book_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Send</button>
</form>
{% endblock content %}

books/templates/book_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Book Detail{% endblock title %}
{% block content %}
<h1 class="middle mt-3 mb-3">Book Detail</h1>
<div class="container">
    <div class="row">
        <div class="col-md-3 mb-4">
            <div class="card h-100">
                <img src="{{ book.cover_pic.url }}" class="card-img-top" alt="{{ book.title }} cover">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">{{ book.description | slice:100 }}</p>
                </div>
            </div> 
        </div>
    </div>
</div>
<h3 class="middle">Comment Add</h3>
<form class="middle-form" action="{% url 'books:book_comment' id=book.id %}" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Send</button>
</form>
{% if book.comments.exists %}
    <h4 style="margin-top: 20px;" class="middle">Comments</h4> <hr>
    {% for comment in book.comments.all %}
        <div class="row mb-3 middle">
            <div class="col-1 me-3">
                <img style="width: 50px; height: 50px; border-radius: 50%;" class="small-profile-pic" src="{{ comment.user.profile_pic.url }}">
            </div>
            <div class="col-7">
                <b>{{ comment.user.username }}</b> rated it {{ comment.star_given }} stars <span class="fw-lighter">{{ comment.created_at }}</span>
                <p class="mt-2 font-monospace">{{ comment.comment }}</p>
            </div>
        </div>
    {% endfor %}
{% endif %}

{% endblock content %}